### PR TITLE
support toml-parser-2.0.0.0

### PR DESCRIPTION
**Pull request by glguy**

### CODE REVIEW

**Comment by henrytill** [comment]
Thanks @glguy, very much appreciated!  

I will go ahead and update the tests.

**Comment by henrytill** [comment]
You beat me to it! :laughing:

**Comment by glguy** [comment]
> You beat me to it! 😆

Oops, I didn't see your message until after I fixed the tests up and came back to see if that fixed the build.

**Comment by henrytill** [comment]
Absolutely no problem, very much appreciated.

**Comment by glguy** [comment]
Before merging this you might consider adding something for making indexing into Tables easier. I had to make tables slightly more annoying to use than they were before in order to have a place to stash all the location annotations. The traversal valueAt defined in the tests now might be worth exporting from the main library (or something like it)

**Comment by henrytill** [comment]
> Before merging this you might consider adding something for making indexing into Tables easier. I had to make tables slightly more annoying to use than they were before in order to have a place to stash all the location annotations. The traversal valueAt defined in the tests now might be worth exporting from the main library (or something like it)

Indeed, I had a similar intuition while looking at the changes.  

I will probably go ahead and merge this PR as-is and then follow up with such a change before releasing to Hackage.

**Pull request merged**
